FROM eclipse-temurin:25-jdk-alpine

WORKDIR /app

RUN apk add --no-cache maven

COPY pom.xml .
COPY src src

ARG API_GATEWAY_CONTAINER_PORT
EXPOSE ${API_GATEWAY_CONTAINER_PORT}

CMD ["mvn", "spring-boot:run", "-Dspring-boot.run.fork=false"]
