FROM eclipse-temurin:25-jdk-alpine

WORKDIR /app

RUN apk add --no-cache maven

COPY pom.xml .
COPY api-gateway/pom.xml api-gateway/pom.xml
COPY api-gateway/src api-gateway/src

WORKDIR /app/api-gateway

ARG API_GATEWAY_CONTAINER_PORT
EXPOSE ${API_GATEWAY_CONTAINER_PORT}

CMD ["mvn", "spring-boot:run", "-Dspring-boot.run.fork=false"]
