services:
  user-service-db:
    image: postgres:18.3-alpine
    container_name: cicipin-user-service-db
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${USER_SERVICE_DB_USER}
      POSTGRES_PASSWORD: ${USER_SERVICE_DB_PASSWORD}
      POSTGRES_DB: ${USER_SERVICE_DB_NAME}
      PGPORT: ${USER_SERVICE_DB_CONTAINER_PORT}
    ports:
      - "${USER_SERVICE_DB_HOST_PORT}:${USER_SERVICE_DB_CONTAINER_PORT}"
    volumes:
      - cicipin-user-service-db-data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${USER_SERVICE_DB_USER} -d ${USER_SERVICE_DB_NAME} -p ${USER_SERVICE_DB_CONTAINER_PORT}"]
      interval: 10s
      timeout: 5s
      retries: 5

  user-service:
    build:
      context: .
      dockerfile: user-service/Dockerfile
      args:
        USER_SERVICE_CONTAINER_PORT: ${USER_SERVICE_CONTAINER_PORT}
    container_name: cicipin-user-service
    env_file:
      - .env
    ports:
      - "${USER_SERVICE_HOST_PORT}:${USER_SERVICE_CONTAINER_PORT}"
    depends_on:
      user-service-db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://cicipin-user-service-db:${USER_SERVICE_DB_CONTAINER_PORT}/${USER_SERVICE_DB_NAME}
      SPRING_DATASOURCE_USERNAME: ${USER_SERVICE_DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${USER_SERVICE_DB_PASSWORD}

  email-service:
    build:
      context: .
      dockerfile: email-service/Dockerfile
      args:
        EMAIL_SERVICE_CONTAINER_PORT: ${EMAIL_SERVICE_CONTAINER_PORT}
    container_name: cicipin-email-service
    env_file:
      - .env
    ports:
      - "${EMAIL_SERVICE_HOST_PORT}:${EMAIL_SERVICE_CONTAINER_PORT}"
    environment:
      EMAIL_SERVICE_CONTAINER_PORT: ${EMAIL_SERVICE_CONTAINER_PORT}
      MAIL_HOST: ${MAIL_HOST}
      MAIL_PORT: ${MAIL_PORT}
      MAIL_USERNAME: ${MAIL_USERNAME}
      MAIL_PASSWORD: ${MAIL_PASSWORD}
      MAIL_FROM: ${MAIL_FROM}
      APP_NAME: ${APP_NAME}

  api-gateway:
    build:
      context: .
      dockerfile: api-gateway/Dockerfile
      args:
        API_GATEWAY_CONTAINER_PORT: ${API_GATEWAY_CONTAINER_PORT}
    container_name: cicipin-api-gateway
    env_file:
      - .env
    ports:
      - "${API_GATEWAY_HOST_PORT}:${API_GATEWAY_CONTAINER_PORT}"
    depends_on:
      - user-service
      - email-service

volumes:
  cicipin-user-service-db-data:
