services:
  user-service-db:
    image: postgres:18.3-alpine
    container_name: cicipin-user-service-db
    env_file:
      - .env.dev
    environment:
      POSTGRES_USER: ${USER_SERVICE_DB_USER}
      POSTGRES_PASSWORD: ${USER_SERVICE_DB_PASSWORD}
      POSTGRES_DB: ${USER_SERVICE_DB_NAME}
      PGPORT: ${USER_SERVICE_DB_CONTAINER_PORT}
    ports:
      - "${USER_SERVICE_DB_HOST_PORT}:${USER_SERVICE_DB_CONTAINER_PORT}"
    volumes:
      - cicipin-user-service-db-data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${USER_SERVICE_DB_USER} -d ${USER_SERVICE_DB_NAME} -p ${USER_SERVICE_DB_CONTAINER_PORT}"]
      interval: 10s
      timeout: 5s
      retries: 5

  user-service:
    build:
      context: .
      dockerfile: user-service/Dockerfile.dev
      args:
        USER_SERVICE_CONTAINER_PORT: ${USER_SERVICE_CONTAINER_PORT}
    container_name: cicipin-user-service
    env_file:
      - .env.dev
    ports:
      - "${USER_SERVICE_HOST_PORT}:${USER_SERVICE_CONTAINER_PORT}"
    depends_on:
      user-service-db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://cicipin-user-service-db:${USER_SERVICE_DB_CONTAINER_PORT}/${USER_SERVICE_DB_NAME}
      SPRING_DATASOURCE_USERNAME: ${USER_SERVICE_DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${USER_SERVICE_DB_PASSWORD}
      SPRING_PROFILES_ACTIVE: dev
    volumes:
      - ./user-service/src:/app/user-service/src
      - ./user-service/pom.xml:/app/user-service/pom.xml
      - ./pom.xml:/app/pom.xml
      - cicipin-maven-cache:/root/.m2

  api-gateway:
    build:
      context: .
      dockerfile: api-gateway/Dockerfile.dev
      args:
        API_GATEWAY_CONTAINER_PORT: ${API_GATEWAY_CONTAINER_PORT}
    container_name: cicipin-api-gateway
    env_file:
      - .env.dev
    ports:
      - "${API_GATEWAY_HOST_PORT}:${API_GATEWAY_CONTAINER_PORT}"
    depends_on:
      - user-service
    environment:
      SPRING_PROFILES_ACTIVE: dev
    volumes:
      - ./api-gateway/src:/app/api-gateway/src
      - ./api-gateway/pom.xml:/app/api-gateway/pom.xml
      - ./pom.xml:/app/pom.xml
      - cicipin-maven-cache:/root/.m2

volumes:
  cicipin-user-service-db-data:
  cicipin-maven-cache:
