FROM eclipse-temurin:25-jdk-alpine

WORKDIR /app

RUN apk add --no-cache maven

COPY pom.xml .
COPY email-service/pom.xml email-service/pom.xml
COPY email-service/src email-service/src

WORKDIR /app/email-service

ARG EMAIL_SERVICE_CONTAINER_PORT
EXPOSE ${EMAIL_SERVICE_CONTAINER_PORT}

CMD ["mvn", "spring-boot:run", "-Dspring-boot.run.fork=false", "-Dspring-boot.run.addResources=true"]
