FROM eclipse-temurin:25-jdk-alpine

WORKDIR /app

RUN apk add --no-cache maven

COPY pom.xml .
COPY src src

ARG USER_SERVICE_CONTAINER_PORT
EXPOSE ${USER_SERVICE_CONTAINER_PORT}

CMD ["mvn", "spring-boot:run", "-Dspring-boot.run.fork=false", "-Dspring-boot.run.addResources=true"]
